# Use a stable Node.js image
FROM node:22-alpine

# Set working directory
WORKDIR /Nodeapp


# Increase memory & stack size
ENV NODE_OPTIONS="--max-old-space-size=16384 "

# Copy dependency files first
COPY package.json yarn.lock ./

# Install dependencies efficiently
RUN yarn cache clean --force && yarn install 

# Copy env file 
COPY .env .env



# Copy the rest of the application
COPY . .

# Build the application with increased memory
RUN  yarn build


# Expose port
EXPOSE 5000

# Start the app
CMD ["yarn", "start"]